name: test_uygulama
description: "Mesai Takip"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Paket buraya eklendi

# BU KISIM EN SOLDA OLMALI (Hizalamayı düzelttim)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true